### ISSUE TITLE
Add support for writing AVIF images

### ISSUE THREAD

**Issue by mridang** [umjammer/vavi-image-avif#5]
It would be great if we could write AVIF from Java. Id had asked this question ages ago but never found a solution. https://stackoverflow.com/questions/63357845/how-can-i-encode-an-image-into-avif-using-java

**Comment by mridang** [comment]
I am willing to contribute but I could do with some guidance here.

**Comment by umjammer** [comment]
https://github.com/umjammer/vavi-image-avif/releases/tag/0.0.4

it has already been implemented.
